# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import memory_service_pb2 as memory__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in memory_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeshMindServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestMemories = channel.unary_unary(
                '/meshmind.api.v1.MeshMindService/IngestMemories',
                request_serializer=memory__service__pb2.IngestMemoriesRequest.SerializeToString,
                response_deserializer=memory__service__pb2.IngestMemoriesResponse.FromString,
                _registered_method=True)
        self.IngestTriplets = channel.unary_unary(
                '/meshmind.api.v1.MeshMindService/IngestTriplets',
                request_serializer=memory__service__pb2.IngestTripletsRequest.SerializeToString,
                response_deserializer=memory__service__pb2.IngestTripletsResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/meshmind.api.v1.MeshMindService/Search',
                request_serializer=memory__service__pb2.SearchPayload.SerializeToString,
                response_deserializer=memory__service__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.MemoryCounts = channel.unary_unary(
                '/meshmind.api.v1.MeshMindService/MemoryCounts',
                request_serializer=memory__service__pb2.MemoryCountsRequest.SerializeToString,
                response_deserializer=memory__service__pb2.MemoryCountsResponse.FromString,
                _registered_method=True)


class MeshMindServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestMemories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestTriplets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MemoryCounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshMindServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestMemories': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestMemories,
                    request_deserializer=memory__service__pb2.IngestMemoriesRequest.FromString,
                    response_serializer=memory__service__pb2.IngestMemoriesResponse.SerializeToString,
            ),
            'IngestTriplets': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestTriplets,
                    request_deserializer=memory__service__pb2.IngestTripletsRequest.FromString,
                    response_serializer=memory__service__pb2.IngestTripletsResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=memory__service__pb2.SearchPayload.FromString,
                    response_serializer=memory__service__pb2.SearchResponse.SerializeToString,
            ),
            'MemoryCounts': grpc.unary_unary_rpc_method_handler(
                    servicer.MemoryCounts,
                    request_deserializer=memory__service__pb2.MemoryCountsRequest.FromString,
                    response_serializer=memory__service__pb2.MemoryCountsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'meshmind.api.v1.MeshMindService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('meshmind.api.v1.MeshMindService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshMindService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestMemories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshmind.api.v1.MeshMindService/IngestMemories',
            memory__service__pb2.IngestMemoriesRequest.SerializeToString,
            memory__service__pb2.IngestMemoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestTriplets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshmind.api.v1.MeshMindService/IngestTriplets',
            memory__service__pb2.IngestTripletsRequest.SerializeToString,
            memory__service__pb2.IngestTripletsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshmind.api.v1.MeshMindService/Search',
            memory__service__pb2.SearchPayload.SerializeToString,
            memory__service__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MemoryCounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/meshmind.api.v1.MeshMindService/MemoryCounts',
            memory__service__pb2.MemoryCountsRequest.SerializeToString,
            memory__service__pb2.MemoryCountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
